algorithm: "noisy_max" # "noisy_sum", "noisy_max", "noisy_arg_max(実装中)"
noisy_var: 
  lower: -60
  upper: 80
  sampling_num: 5000
integral: "gauss" # "gauss"(ガウス積分), "trapz"(台形近似)
search: 
  way: "threshold" # "all", "threshold"
  threshold: 0.1
