algorithm: "noisy_arg_max_cdf" # "noisy_sum", "noisy_max", "noisy_hist", "noisy_arg_max(実装中)", "noisy_max_cdf", "noisy_arg_max_cdf"
noisy_var: 
  lower: -60
  upper: 80
  sampling_num: 1000
integral: "gauss" # "gauss"(ガウス積分), "trapz"(台形近似)
search: 
  way: "all" # "all", "threshold"
  threshold: 0.1
